### ISSUE TITLE
LICK does not support wary-5.5.iso

### ISSUE THREAD

**Issue by kuituhirvi** [noryb009/lick#25]
The last WaryPuppy release is not working with the latest LICK release on Windows XP.

**Comment by noryb009** [comment]
I was able to install Wary-5.5 on XP without any problems. What problem do you run into? Do other ISOs work?

**Comment by kuituhirvi** [comment]
Got a message stating that the ISO is not supported. Installed via Wary_511.exe and Grub4Dos from LICK, so updating to 5.5 should be possible from that. But will verify the condition of the Wary-5.5.iso now.

**Comment by noryb009** [comment]
@kuituhirvi Ah sorry, I just saw your edit.

I still can't reproduce your issue, nor can I figure out where the error is being generated. Could you give me the exact error message? Do other ISOs work in LICK?

**Comment by kuituhirvi** [comment]
No problem and sorry but can't currently add anything, gave it to use with Wary 5.1. Before reading instructions tried it with Debian 9.3, which gave the exact same message. And would not want to try with any other ISO, because it is 256 MB single core machine.  

Will post more information when I get the machine back.

**Comment by noryb009** [comment]
I'm closing this issue for now, since I still cannot reproduce the problem. Once you get the machine back we can reopen the issue and go from there.

**Comment by kuituhirvi** [comment]
So it installed with the cli version, the graphical window still says "Please provide a valid ISO." Maybe should've filled out ID and other forms beforehand or something like that...

**Comment by noryb009** [comment]
It's good that the cli version worked - it means that the issue is a GUI issue, not some backend issue.

Try the GUI in [this download](https://csclub.uwaterloo.ca/~lalorime/lick/1.2.1-testing2/).

* There is new drag and drop code for #15, it might fix this issue as well.
* I fixed a buffer overflow, which might cause this problem.
* I added some extra logging. If dropping an ISO to the window doesn't work OR clicking then selecting an ISO doesn't work, please upload the log.

**Comment by kuituhirvi** [comment]
The new version worked perfectly. Good job! It was nice "working" with you. :)
