### ISSUE TITLE
Better initrd selection logic

### ISSUE THREAD

**Issue by noryb009** [noryb009/lick#32]
[As mentioned on the forum](http://www.murga-linux.com/puppy/viewtopic.php?p=1019292#1019292), FatDog has two initrd files, `initrd` and `initrd-nano.xz`. LICK selects the nano, while it should select the former.

**Comment by noryb009** [comment]
[This blogpost](http://www.lightofdawn.org/blog/?viewDetailed=00181) explains what it's used for: loading the normal initrd, which is useful if the bootloader reads files from disk slowly. I'm not sure why the normal initrd can't be found (I was able to see the file in a initrd-nano command line).

I think the easiest way to work around this for now is that if there are multiple initrd files, use the one with the shortest name. I think this will work in most cases because "special" initrd files usually contain suffixes.

**Comment by noryb009** [comment]
[This page](http://distro.ibiblio.org/fatdog/web/faqs/huge-initrd.html) says that initrd-nano needs a [mergeinitrd](http://distro.ibiblio.org/fatdog/web/faqs/boot-options.html#mergeinitrd) parameter, explaining why the initrd wasn't found.

**Comment by jamesbond3142** [comment]
Thanks for looking into this!

For a installed Fatdog, if the BIOS supports it, it's better to use the huge "initrd" directly, because if you choose to use the nano initrd, you need to specify the path to the huge initrd (this is what "mergeinitrd" parameter does) so the nano initrd can find and load it. I'm not sure how easy it is to map Windows path and drive names (C:, D: etc) to Linux path and drive names (sda, sdb, etc), although you could make it more generic by using partition volume labels instead of drive names.

**Comment by noryb009** [comment]
Thanks for the comment! For now, I'll just use `initrd` because it's easier, and users can switch to the nano initrd if they want.

**Comment by jamesbond3142** [comment]
Agreed.

However, I just looked at your commit. You are comparing the length of the "initrd" filename against i->initrd; but this i->initrd is the combined full name of the destination (because it comes from  menu_path(concat_strs(3, dst, "/", n)); so wouldn't it be that i->initrd is always longer than "n" and therefore it always gets replaced?

**Comment by noryb009** [comment]
Whoops! You're absolutely right, I'll fix that soon.

It seems like the list of files is in reverse alphabetical order, so `initrd` is always chosen for Fatdog, which explains why I didn't see this bug while testing. Regardless, this should be fixed.

**Comment by noryb009** [comment]
Good eye, thanks for the catch! I should really start working on #23

**Comment by jamesbond3142** [comment]
Thanks for the quick fix, looks ok now. :+1: 

Are you going to re-issue v1.3.2 or are you going to go for v1.3.3? (asking since we're probably going for final release soon and would like to get this in the release ISO).

Just FYI: I tested LICK (v1.3.2, before the corrected fix) on wine - it didn't work, it said "missing bcdedit". I tried that on ReactOS LiveCD, also failed - cannot find "boot.ini". (I would have tested on installed ReactOS too but that thing went BSOD on first boot ...). Anyway, the point is,  this error message is all good, meaning that LICK has an extensive sanity checks and refuses to continue when things don't look all right :+1:

**Comment by noryb009** [comment]
I'll release 1.3.3 shortly, probably in the next hour or so. If I were to rerelease 1.3.2, it would just cause confusion, and I'm not a big fan of 1.3.2.1 being a thing. BTW, thanks again for including LICK on the Fatdog ISO!

There's a ridiculous amount of code in LICK to deal with weird edge cases to try to put the system back into a state that would at least boot. It's good to see that some of the code seems to work in practice :)

**Comment by jamesbond3142** [comment]
> There's a ridiculous amount of code in LICK to deal with weird edge cases to try to put the system back into a state that would at least boot. It's good to see that some of the code seems to work in practice :)

I know exactly what you mean. We have installers for Fatdog and I have to go into paranoia mode to ensure that we don't accidentally clobber the target system :)

Thank you for the update, I have committed it to Fatdog and we'll have it for the final release.
