### ISSUE TITLE
Error installing loader in Windows 10 x86 BIOS mode

### ISSUE THREAD

**Issue by alw1746** [noryb009/lick#37]
I have 2 2009-era Acer Aspire One laptops running Win 10 Pro which I'm trying to dual-boot with puppy linux. The Z520 cpu model worked fine but the N280 cpu failed with Error installing loader!. Both boot up using legacy BIOS mode.  My suspicion is it's a Win 10 problem, which on the failed N280 is the latest v2004, while the Z520 still runs v1909. I've attached msinfo/bcdedit logs from the good and failed laptops and also the output log of the Lick trace version. My feeing is it's a permission or security issue caused by v2004 patch. Is it possible to create a verbose trace version for in-depth diagnosis? As a workaround, can I manually create the BCD bootloader entry using bcdedit, then install the ISO with Lick?

[failPC_msinfo.txt](https://github.com/noryb009/lick/files/5286564/failPC_msinfo.txt)
[goodPC_bcdedit.txt](https://github.com/noryb009/lick/files/5286565/goodPC_bcdedit.txt)
[goodPC_msinfo.txt](https://github.com/noryb009/lick/files/5286566/goodPC_msinfo.txt)
[failPC_bcdedit.txt](https://github.com/noryb009/lick/files/5286567/failPC_bcdedit.txt)
[failPC_lick_cli_trace.log](https://github.com/noryb009/lick/files/5286568/failPC_lick_cli_trace.log)

**Comment by noryb009** [comment]
Hi Alex,

Thanks for including the log! It looks like it's having trouble mounting the UEFI drive. What the code does is:

* Finds an unused drive letter (I think it starts at `Z:\` and works backwards until it finds an unused drive letter)
* Runs the command `mountvol Z: /S` which will mount the UEFI drive in the Z drive. This is run with administrator privileges.
* After that command, the drive is mounted, but can only be accessed through command prompt (not the file explorer GUI).
* Later, the drive is unmounted with `mountvol Z: /D`

1) Do you have a UEFI partition still? I'm not sure if legacy mode might no longer have one.
2) Could you open an administrator command prompt and play around with the `mountvol Z: /S` command? That should tell us what's going wrong.

Thanks!

**Comment by alw1746** [comment]
Hi Luke,

Both laptops run 32-bit Win 10 Pro and I found it does not have the /S option. So it's a puzzle on how Lick worked for the Z520 cpu. Both of my C: drives are MBR disks, I do not have any UEFI partitions and there are no UEFI boot options in the bios. Just to recap, my intention is to dual-boot Win 10/puppy linux on C: I do not have any other drives.

[failPC_mountvol.txt](https://github.com/noryb009/lick/files/5287983/failPC_mountvol.txt)

**Comment by alw1746** [comment]
On both laptops, I did a mountvol Z:\ <volname of System Reserved partition>. Worked fine so access to the MBR partition is not a problem. Is Lick having a problem running the mountvol command? Does it spawn a CMD process to run it?

**Comment by noryb009** [comment]
Based on your comment about _both_ computers not having the `/S` option in `mountvol /?`, the "good" computer should have also had this error. It didn't, which suggests the issue is with detecting whether the system is in UEFI or MBR mode, [which is controlled by this](https://github.com/noryb009/lick/blob/04f2de14bdf0df70133d402875b7ab0af6d08ec6/liblick/system-info.c#L94). Looking at [the documentation](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getfirmwareenvironmentvariablea) for `GetFirmwareEnvironmentVariableA`:

> On a legacy BIOS-based system, or on a system that supports both legacy BIOS and UEFI where Windows was installed using legacy BIOS, the function will fail with ERROR_INVALID_FUNCTION

It doesn't appear that's the case here. I've written a little program to see what happens on your systems, could you run it and see what the result is? I included the original source, compiled with `i686-w64-mingw32-gcc bios-or-not.c -o bios-or-not.exe -static`:

[bios-or-not.zip](https://github.com/noryb009/lick/files/5288924/bios-or-not.zip)

Thanks again for the help :)

**Comment by alw1746** [comment]
Attached the output from good/bad laptops. The getfirmware func on the bad PC returned 1314 which equates to "required privilege is not held by the client".  The good PC returned 0 which means bios mode detected. Seems like there is some permission-related issue on bad PC that is preventing the func from retrieving the firmware env variable. It's unlikely to be UEFI-related since there are no UEFI partition or bios setup on the PC. 
[badPC_results.log](https://github.com/noryb009/lick/files/5291689/badPC_results.log)
[goodPC_results.log](https://github.com/noryb009/lick/files/5291690/goodPC_results.log)

**Comment by noryb009** [comment]
Hey, thanks for running those! I agree, it looks like it is a privilege issue. The documentation I referenced above does mention that it needs `SE_SYSTEM_ENVIRONMENT_NAME`, so I suspect that is where the issue is. Could you try this out on the bad PC and let me know the output? Thanks in advance :)

Compiled using `i686-w64-mingw32-g++ bios-or-not.cc -o bios-or-not.exe -static`

[bios-or-not.zip](https://github.com/noryb009/lick/files/5297244/bios-or-not.zip)

**Comment by alw1746** [comment]
The log shows it detected BIOS mode after SE_SYSTEM_ENVIRONMENT_NAME was enabled. Looks like this has done the trick. Not sure about the OpenThreadToken failed error. On a separate test, I cloned the good PC disk to the bad and I could run Lick successfully so it points to a Windows issue, not hardware or bios setup. I also did a clone from bad PC to another PC and this 3rd PC had the same Lick failure. Seems the MS doc is a bit misleading, it should perhaps say "the func will always fail with ERROR_INVALID_FUNCTION _but only if you call it with the SE... priv enabled._"

[bios.log](https://github.com/noryb009/lick/files/5309593/bios.log)

**Comment by noryb009** [comment]
Thanks for running that!

I think I've resolved the issue now, could you test this out before I do the official release?

[LICK-1.3.3-win32.zip](https://github.com/noryb009/lick/files/5322387/LICK-1.3.3-win32.zip)

**Comment by alw1746** [comment]
It's working good now Lukas, I can install Lick and PL on my C: without any errors. There is one odd issue which I don't think is Lick-related. On restart, Win10 fails to boot with some device error. It then goes thru 2 restarts, a disk diagnostics and finally an automatic repair. Subsequently it boots up without further problems. Probably a dirty NTFS was somehow detected and forced a chkdsk repair. PL boots up without any problems. Anyway, thanks for all your good work and quick responses, you can close this request now if you like.

**Comment by noryb009** [comment]
It _sounds_ like that the chkdsk isn't related, but it's hard to tell.

I'll release a new version of LICK with these changes soon (after I get NSIS working again...)

Thanks again for all your help with testing!
