### ISSUE TITLE
having boot problem with Fossapup64 9.5 installed using Lick

### ISSUE THREAD

**Issue by bigpup1** [noryb009/lick#56]
noryb009,

Would you please look at this problem posted on the Puppy Linux forum.
Lick installed Fossapup64 9.5, but it will not boot when selected in the boot menu.
https://forum.puppylinux.com/viewtopic.php?t=5276

If you look at the posts in this topic.
A lot of info is given about what is going on.
Even has a video posted of exactly what happens.
On 3rd page of topic, has post showing the boot menu entry used to boot Fossapup64 9.5

We are running out of ideas.

Puppy forum is constantly telling people to use Lick.
We all want this problem solved!

**Comment by noryb009** [comment]
Thanks for notifying me, I posted a response. It almost looks like either grub2 gets stuck on the `search` (maybe looking at some weird partition?), or the boot gets stuck on the `fsck` - but I'll first ask about why they think it has to do with the extraction.

Anyways, closing this issue, since the discussion was moved over to the forum.
